import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { sanityClient } from "@/sanity";
import { siteSettingsQuery } from "@/lib/sanity.queries";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import FloatingLogo from "@/components/FloatingLogo";
import PageTransitionWrapper from "@/components/PageTransitionWrapper";
import Preloader from "@/components/Preloader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const settings = await sanityClient.fetch(siteSettingsQuery)

  // Carica l'SVG del logo lato server se disponibile
  let logoSvgContent = null
  const logoSvgUrl = settings?.logoSvg?.asset?.url
  if (logoSvgUrl && typeof logoSvgUrl === 'string' && (logoSvgUrl.startsWith('http') || logoSvgUrl.startsWith('https'))) {
    try {
      const controller = new AbortController()
      const timeoutId = setTimeout(() => controller.abort(), 5000) // Timeout di 5 secondi
      
      const svgResponse = await fetch(logoSvgUrl, {
        cache: 'no-store',
        signal: controller.signal
      }).catch((fetchError) => {
        // Se il fetch fallisce, ritorna null invece di lanciare errore
        if (process.env.NODE_ENV === 'development') {
          console.warn('Error fetching logo SVG:', fetchError.message)
        }
        return null
      })
      
      clearTimeout(timeoutId)
      
      if (svgResponse && svgResponse.ok) {
        const svgText = await svgResponse.text()
        // Sostituisci fill e stroke con currentColor
        logoSvgContent = svgText
          .replace(/fill="(?!none)[^"]*"/g, 'fill="currentColor"')
          .replace(/stroke="(?!none)[^"]*"/g, 'stroke="currentColor"')
          .replace(/fill='(?!none)[^']*'/g, "fill='currentColor'")
          .replace(/stroke='(?!none)[^']*'/g, "stroke='currentColor'")
          .replace(
            /<svg([^>]*)>/,
            '<svg$1 style="max-width: 80px; max-height: 80px; width: auto; height: auto; color: inherit; fill: currentColor;">'
          )
      }
    } catch (error) {
      // Gestisci silenziosamente l'errore senza bloccare il rendering
      if (process.env.NODE_ENV === 'development') {
        console.warn('Error loading footer logo SVG:', error.message)
      }
    }
  }

  // Genera @font-face per i custom fonts
  const customFontStyles = settings?.customFonts?.map((font) => {
    if (!font.familyName) return null
    
    const fontFamily = font.familyName
    const fontWeight = font.fontWeight || '400'
    const fontStyle = font.fontStyle || 'normal'
    
    // Se c'è un URL del font (es. Google Fonts)
    if (font.fontUrl) {
      return `@import url('${font.fontUrl}');`
    }
    
    // Se c'è un file font caricato
    if (font.fontFile?.asset?.url) {
      const fontUrl = font.fontFile.asset.url
      const fileExtension = fontUrl.split('.').pop()?.toLowerCase()
      let format = 'woff2'
      
      if (fileExtension === 'woff') format = 'woff'
      else if (fileExtension === 'woff2') format = 'woff2'
      else if (fileExtension === 'ttf') format = 'truetype'
      else if (fileExtension === 'otf') format = 'opentype'
      
      // Per Safari: se il font è WOFF2, aggiungi anche una versione senza format() come fallback
      // Safari a volte ha problemi con il format() specificato per WOFF2
      // Se il font è già TTF, usalo direttamente (Safari lo preferisce)
      let srcDeclaration = `url('${fontUrl}') format('${format}')`
      
      // Se è WOFF2 e Safari potrebbe avere problemi, aggiungi fallback senza format
      if (format === 'woff2') {
        // Safari può avere problemi con WOFF2, quindi aggiungiamo anche senza format come fallback
        srcDeclaration = `url('${fontUrl}') format('woff2'), url('${fontUrl}')`
      }
      
      return `
        @font-face {
          font-family: '${fontFamily}';
          src: ${srcDeclaration};
          font-weight: ${fontWeight};
          font-style: ${fontStyle};
          font-display: swap;
          /* Fix per Safari: assicura che il font venga caricato correttamente */
          -webkit-font-smoothing: antialiased;
          -moz-osx-font-smoothing: grayscale;
        }
      `
    }
    
    return null
  }).filter(Boolean).join('\n')


  return (
    <html lang="en">
      <head>
        {customFontStyles && (
          <style dangerouslySetInnerHTML={{ __html: customFontStyles }} />
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          // Le variabili CSS per font vengono impostate da Header.jsx quando si cambia font
          // I colori vengono gestiti da Header.jsx quando si cambia colore
        }}
      >
        <Preloader
          logoSvg={settings?.logoSvg}
          logo={settings?.logo}
        />
        <Header
          menuSubtitle={settings?.menuSubtitle || ''}
          logo={settings?.logo}
          logoSvg={settings?.logoSvg}
          logoSvgContent={logoSvgContent}
        />
        <PageTransitionWrapper>
          <div className="siteContainer">
            {children}
          </div>
        </PageTransitionWrapper>
        <Footer 
          contactInfo={settings?.contactInfo}
          legal={settings?.legal}
          logoSvg={settings?.logoSvg}
          logoSvgContent={logoSvgContent}
          social={settings?.social}
        />
      </body>
    </html>
  );
}
